[package]
name = "docker-rust-ci-base"
version = "0.1.0"
authors = ["Dany Laporte <dany_laporte@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "1.1"
actix-web = "2.0"
aes-gcm = "0.6"
base64 = "0.12"
bincode = "1.3"
blake3 = "0.3"
chrono = { version = "0.4", features = ["serde"] }
envy = "0.4"
fnv = "1.0"
hex-serde = "0.1"
once_cell = "1.4"
parking_lot = "0.11"
regex = "1.3"
rocksdb = { version = "0.14", default-features = false, features = ["zstd"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio = { version = "0.2", features = ["sync"] }
uuid = { version = "0.8", features = ["v4", "serde"] }
